#!/usr/bin/perl

$A   =     ; # cross sectional area in meters**2
$m   =     ; # mass of rocket
$T   =     ; # Thrust of motor in Newtons
$t   =     ; # thrust burn time
$g   = 9.81; # gravitational constant meter/sec**2
$rho = 1.22; # density of air  kg/meter**3
$Cd  = 0.75; # coeficient of drag for most rockets (no units)

$k   = 1/2*$rho*$Cd*$A;
$q   = sqrt(($T - $m*$g)*$k/$m);
